version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
    vendor: true
    reviewers:
      - "benburkert"
      - "danbernier"
      - "geemus"
